$path = "C:\Users\alisa\Desktop\dorkiklim\4iklim-next\app\page.tsx"
$content = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)
$content = $content.Replace('ÄŸ', 'ğ')
$content = $content.Replace('Äž', 'Ğ')
$content = $content.Replace('Ä°', 'İ')
$content = $content.Replace('Ä±', 'ı')
$content = $content.Replace('ÅŸ', 'ş')
$content = $content.Replace('Åž', 'Ş')
$content = $content.Replace('Ã§', 'ç')
$content = $content.Replace('Ã‡', 'Ç')
$content = $content.Replace('Ã¼', 'ü')
$content = $content.Replace('Ãœ', 'Ü')
$content = $content.Replace('Ã¶', 'ö')
$content = $content.Replace('Ã–', 'Ö')
$content = $content.Replace('Ã¢', 'â')
$content = $content.Replace('â‚º', '₺')
[System.IO.File]::WriteAllText($path, $content, [System.Text.UTF8Encoding]::new($false))
Write-Host "DONE"
